
# Generated by CodiumAI
from tarot import Tarot


import pytest

class TestTarot:

    # Initialize Tarot class with valid deck directory
    def test_initialize_with_valid_deck_directory(self):
        deck_directory = "path/to/deck"
        tarot = Tarot(deck_directory)
    
        assert tarot.deck_directory == deck_directory
        assert isinstance(tarot.library, str)
        assert isinstance(tarot.drawn_cards, list)


    